#
# Module manifest for module 'Worker369.AWS'
#
# Generated by: Sirius Chan
#
# Generated on: 10/2/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Worker369.AWS.psm1'

# Version number of this module.
ModuleVersion = '0.0.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'b50a4b4c-1b25-465b-8810-642020472585'

# Author of this module
Author = 'Sirius Chan'

# Company or vendor of this module
CompanyName = 'Sirius Chan'

# Copyright statement for this module
Copyright = '(c) Sirius Chan. All rights reserved.'

# Description of the functionality provided by this module
# Description = ''

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.2'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module.
# This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module.
# This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(
    'Worker369.Utility',
    'AWS.Tools.Common',
    'AWS.Tools.CloudWatch',
    'AWS.Tools.CloudWatchLogs',
    'AWS.Tools.SecurityToken',
    'AWS.Tools.IdentityManagement',
    'AWS.Tools.EC2',
    'AWS.Tools.CloudFormation',
    'AWS.Tools.IdentityStore',
    'AWS.Tools.Lambda',
    'AWS.Tools.S3',
    'AWS.Tools.SimpleEmailV2',
    'AWS.Tools.SSOAdmin',
    'AWS.Tools.Organizations'
)

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry,
# use an empty array if there are no functions to export.
FunctionsToExport = @(

    # Utilities
    'Get-QueryDefinition',  # Consider to remove if released.
    'Get-ResourceString',   # Consider to remove if released.
    'Get-HintItem',         # Consider to remove if released.
    'New-TagSpecification', # Consider to remove if released.

    # MFA
    'Write-MfaProfile',

    # Prefix list
    'Resolve-PrefixList', 'Write-PrefixList',

    # VPC BPA Exclusion
    'Show-VpcBpaExclusion', 'New-VpcBpaExclusion', 'Edit-VpcBpaExclusion', 'Remove-VpcBpaExclusion',

    # VPC
    'Show-Vpc', 'New-Vpc', 'Rename-Vpc', 'Remove-Vpc',

    # VPC CIDR
    'Add-VpcIpv4Cidr', 'Remove-VpcIpv4Cidr',
    'Add-VpcIpv6Cidr', 'Remove-VpcIpv6Cidr',

    # VPC CIDR Map
    'Show-VpcCidrMap'

    # VPC Attribute
    'Enable-VpcDnsResolution', 'Disable-VpcDnsResolution',
    'Enable-VpcDnsHostnames',  'Disable-VpcDnsHostnames',
    'Enable-VpcNauMetrics',    'Disable-VpcNauMetrics',

    # VPC Peering
    'Show-VpcPeering', 'New-VpcPeering', 'Rename-VpcPeering', 'Remove-VpcPeering',
    'Approve-VpcPeering', 'Deny-VpcPeering',

    # VPC Peering Attributes
    'Enable-VpcPeeringDns', 'Disable-VpcPeeringDns',

    # Internet Gateway,
    'Show-InternetGateway', 'New-InternetGateway', 'Rename-InternetGateway', 'Remove-InternetGateway',
    'Mount-InternetGateway', 'Dismount-InternetGateway',

    # Subnet
    'Show-Subnet', 'New-Subnet', 'Copy-Subnet', 'Rename-Subnet', 'Remove-Subnet',

    # Subnet CIDR
    'Add-SubnetIpv6Cidr', 'Remove-SubnetIpv6Cidr',

    # Subnet Attribute
    'Enable-SubnetAAAARecord',         'Disable-SubnetAAAARecord',
    'Enable-SubnetARecord',            'Disable-SubnetARecord',
    'Enable-SubnetAutoAssignPublicIP', 'Disable-SubnetAutoAssignPublicIP',
    'Enable-SubnetAutoAssignIPv6',     'Disable-SubnetAutoAssignIPv6',
    'Enable-SubnetDns64',              'Disable-SubnetDns64',
    'Set-SubnetHostnameType',

    # Route Table
    'Show-RouteTable', 'New-RouteTable', 'Rename-RouteTable', 'Remove-RouteTable',

    # Default Route Table
    'Get-DefaultRouteTable', 'Set-DefaultRouteTable', 'Clear-DefaultRouteTable',

    # Route Table Association
    'New-RouteTableAssociation', 'Remove-RouteTableAssociation',

    # Route Entry
    'Show-Route', 'Find-Route', 'Add-Route', 'Remove-Route',

    # Network ACL
    'Show-NetworkAcl', 'New-NetworkAcl', 'Rename-NetworkAcl', 'Remove-NetworkAcl',

    # Security Group
    'Show-SecurityGroup', 'New-SecurityGroup', 'Copy-SecurityGroup', 'Clear-SecurityGroup',
    'Rename-SecurityGroup', 'Remove-SecurityGroup',

    # Default Security Group
    'Set-DefaultSecurityGroup', 'Get-DefaultSecurityGroup',

    # Security Group Rule
    'Show-SecurityGroupRule',

    # AWS Organization
    'Show-OrgTree'

    # CloudFormation
    'Show-Stack', 'Show-StackDrift', 'Show-StackInstance', 'Show-StackResource',
    'Show-IacScanBrief', 'Show-IacScanDetail',

    # CloudWatch Alarms
    'New-EC2CpuAlarm', 'New-EC2StatusAlarm',

    # Identity Center
    'Show-SsoAssignment', 'Show-SsoUserPermission',

    # Lambda
    'Show-Lambda',

    # S3
    'Show-S3Folder', 'Show-S3FileContent',

    # SES
    'Send-SesMailMessage',

    # EC2
    'Get-EC2SystemLog'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry,
# use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry,
# use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess.
# This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}